---
- name: Random password generator
  hosts: server1
  become: true
  become_user: root
  tasks:
    - 
      name: Ensuring pwgen is installed
      yum:
        name: secpwgen
        state: present
    
    - 
      name: Generating password
      shell: "pwgen -N 1 -s 30"
      register: output
    
    - 
      name: Printing name of the output
      debug:
        msg: "The password is {{output}}"
