---
- name: Configuring Database
  hosts: server2
  vars_files:
    - vars/myvars.yml
  roles:
    - db

- name: Configuring Wordpress
  hosts: server1
  vars_files:
    - vars/myvars.yml
  roles:
    - app




